name: Setup
description: Setup environment, Node.js, pnpm, and dependencies

inputs:
  port:
    description: Port number for the application
    required: false
    default: '3000'

runs:
  using: 'composite'
  steps:
    - name: Setup .env file
      run: |
        echo "CI=true" >> .env
        echo "BETTER_AUTH_SECRET=dummy_secret_that_has_32_symbols" >> .env
        echo "BETTER_AUTH_URL=http://localhost:${{ inputs.port }}" >> .env
        echo "GOOGLE_CLIENT_ID=dummy_id" >> .env
        echo "GOOGLE_CLIENT_SECRET=dummy_secret" >> .env
        echo "PORT=${{ inputs.port }}" >> .env
      shell: bash
    - name: Setup pnpm
      uses: pnpm/action-setup@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
