sonar.organization=dzmitrydanilovich
sonar.projectKey=DzmitryDanilovich_teapot

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.inclusions=**/*.ts,**/*.tsx
sonar.exclusions=src/generated/**
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/vitest/lcov.info
sonar.coverage.exclusions=src/app/**/page.tsx,src/app/**/layout.tsx,src/components/ui/**/*,src/components/theme-provider.tsx
