name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run ESLint
        run: pnpm lint

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v7'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run TypeScript type checking
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v7'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, check-types, test]
    # env:
    #   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    #   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v7'
      - name: Setup
        uses: ./.github/actions/setup
        # with:
        #   ignore-env: true
      - name: Build the application
        run: pnpm build
          # pnpm exec vercel build
          # --yes
          # --target=${{ github.event_name == 'pull_request' && 'preview' || 'production' }}
          # --token=${{ secrets.VERCEL_TOKEN }}
      - name: Upload .next directory
        uses: actions/upload-artifact@v7
        with:
          name: next-directory
          path: |
            .next
            !.next/cache
          include-hidden-files: true
      # - name: Upload Vercel output
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: vercel-output
      #     path: .vercel/output
      #     include-hidden-files: true

  e2e:
    runs-on: ubuntu-latest
    needs: [build]
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: teapot-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v7'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/teapot-test" >> .env
          echo "NEXT_DIST_DIR='.next'" >> .env
        shell: bash
      - name: Download .next directory
        uses: actions/download-artifact@v7
        with:
          name: next-directory
          path: .next
      - uses: actions/cache@v6
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run end-to-end tests
        run: pnpm e2e
      - name: Upload Playwright Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e]
    permissions:
      contents: read
      pull-requests: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v7'
      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-env: true
      # - name: Restore Vercel output
      #   uses: actions/download-artifact@v7
      #   with:
      #     name: vercel-output
      #     path: .vercel/output
      # - name: Restore .next directory
      #   uses: actions/download-artifact@v7
      #   with:
      #     name: next-directory
      #     path: .next
      - name: Create Neon branch
        if: ${{ github.event_name == 'pull_request' }}
        id: neon
        uses: neondatabase/create-branch-action@v6
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: preview/pr-${{ github.event.pull_request.number }}
          prisma: true
      # co-locate the build instead of downloading the artifacts to prevent hard link issues
      # to be removed in the next task
      - name: Build the application
        run: >-
          pnpm exec vercel build
          --yes
          --target=${{ github.event_name == 'pull_request' && 'preview' || 'production' }}
          --token=${{ secrets.VERCEL_TOKEN }}
      - name: Migrate database
        env: 
          DATABASE_URL: ${{ github.event_name == 'pull_request' && steps.neon.outputs.db_url || secrets.PROD_DB_URL }}
        run: pnpm exec prisma migrate deploy
      - name: Deploy to Vercel
        env: 
          PREVIEW_DATABASE_URL: ${{ steps.neon.outputs.db_url_pooled }}
        run: >-
          pnpm exec vercel deploy
          --yes
          --prebuilt
          ${{ github.event_name != 'pull_request' && '--prod' || '-e DATABASE_URL="$PREVIEW_DATABASE_URL"' }}
          --token=${{ secrets.VERCEL_TOKEN }}
          > deployment_url.txt
      - name: Comment deployment URL on PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh pr comment ${{ github.event.pull_request.number }}
          --body "Preview deployment URL: $(tail -n1 deployment_url.txt)"
