name: Composite PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
  sonar:
    permissions:
     contents: read
    uses: ./.github/workflows/sonar.yml
    needs: test
    secrets: inherit
  deploy-preview:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-preview.yml
    needs: test
    secrets: inherit
  e2e:
    permissions:
      contents: read
    uses: ./.github/workflows/e2e.yml
    needs: deploy-preview
    secrets: inherit
    with:
      baseURL: ${{ needs.deploy-preview.outputs.deployment_url }}
  auto-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/auto-merge.yml
    needs: e2e
    secrets: inherit
