name: Composite Main

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - .github/**/*

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
  deploy-prod:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-prod.yml
    needs: test
    secrets: inherit
  e2e:
    permissions:
      contents: read
    uses: ./.github/workflows/e2e.yml
    needs: deploy-prod
    secrets: inherit
    with:
      baseURL: ${{ needs.deploy-prod.outputs.deployment_url }}
      isProduction: true
  promote:
    permissions:
      contents: read
    uses: ./.github/workflows/promote.yml
    needs: [deploy-prod, e2e]
    secrets: inherit
    with:
      baseURL: ${{ needs.deploy-prod.outputs.deployment_url }}
