name: Deploy Preview
on:
  workflow_call:
    outputs:
      deployment_url:
        description: 'The URL of the preview deployment'
        value: ${{ jobs.deploy.outputs.deployment_url }}
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.set-output.outputs.deployment_url }}
    permissions:
      contents: read
    outputs:
      deployment_url: ${{ steps.set-output.outputs.deployment_url }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7.0.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Create Neon branch
        id: neon
        uses: neondatabase/create-branch-action@72ed4f69a12b6be9c16aebfad893f6a21e9aba8b # 6.4.0
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: preview/pr-${{ github.event.pull_request.number }}
          prisma: true
      - name: Reset Neon branch
        uses: neondatabase/reset-branch-action@470ab8101095ea33737c294d17364a72fd80761b # v1.3.2
        if: ${{ steps.neon.outputs.created == 'false' }}
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: true
          branch: preview/pr-${{ github.event.pull_request.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: Build the application
        run: >-
          pnpm exec vercel build
          --yes
          --target=preview
          --token=${{ secrets.VERCEL_TOKEN }}
      - name: Migrate database
        env: 
          DATABASE_URL: ${{ steps.neon.outputs.db_url }}
        run: pnpm exec prisma migrate deploy
      - name: Deploy to Vercel
        run: >-
          pnpm exec vercel deploy
          --yes
          --prebuilt
          -e DATABASE_URL="${{ steps.neon.outputs.db_url_pooled }}"
          --token=${{ secrets.VERCEL_TOKEN }}
          > deployment_url.txt
      - name: Set deployment URL output
        id: set-output
        run: echo "deployment_url=$(tail -n1 deployment_url.txt)" >> $GITHUB_OUTPUT
