name: Cleanup preview DB

on: 
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: preview/pr-${{ github.event.pull_request.number }}
