name: Cleanup preview DB

on: 
  pull_request:
    types: [closed]
  workflow_call:

jobs:
  delete-neon-branch:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@4468d825d5a88ef4012f1705a82f02ec3072f776 # v3.2.1
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: preview/pr-${{ github.event.pull_request.number }}
